spring:
  application:
    name: admin-shop
  # mysql数据库
  datasource:
    url: jdbc:mysql://10.20.0.233:3306/zzzgd
#    url: jdbc:mysql://192.168.2.233:3306/zzzgd
    username: root
    password: zhangguodong
    #指定数据库连接池为hikari
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池
    hikari:
      allow-pool-suspension: true
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数,默认是10
      maximum-pool-size: 10
      # 测试连接查询语句
      connection-test-query: SELECT 1
      # 连接超时时间 默认30s
      connection-timeout: 30000
      # 一个连接的生命时长（毫秒） 默认30分钟,强烈建议设置比数据库超时时长少30秒
      #查询show GLOBAL variables like '%timeout';找到wait_timeout,mysql默认是28800s,即8个小时
      max-lifetime: 1800000


# mybatis
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zgd.shop.dao.entity.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-prefix: 'dao.'


server:
  port: 8089
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.zaxxer.hikari: INFO

user-auth:
#  sessionExpirationTime: 24 * 60 * 60 * 1000
  jwtExpirationTime: 60000



